<a href="https://colab.research.google.com/github/Gayatri-bit-bit/gayatri---Python/blob/main/IAP_Day_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
# Step 1: Read an array from the user
# Let's assume the user enters 9 elements for the matrix
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Step 2: Display the array
print("\nOriginal Array:")
print(a)

# Step 3: Resize the array to a 3x3 matrix
a = a.reshape(3, 3)
print("\nResized to 3x3 Matrix:")
print(a)

# Step 4: Create a random 3x3 matrix
b = np.random.randint(1, 10, (3, 3))  # Generate random integers between 1 and 9
print("\nRandom 3x3 Matrix:")
print(b)

# 5.1 Matrix Addition
sum = np.add(a, b)
print("\nMatrix Addition (A + B):")
print(sum)
# 5.2: Matrix Subtraction
sub = np.subtract(a, b)
print("\nMatrix Subtraction (A - B):")
print(sub)


# 5.3: Matrix Multiplication (Element-wise product)
mul = np.dot(a, b)  # or you can use a @ b for matrix multiplication
print("\nMatrix Multiplication (a * b):")
print(mul)

# 5.4: Cross Product (Only for 3x3 matrices, row-wise)
cross = np.cross(a, b)
print("\nCross Product (Row-wise A x B):")
print(cross)

# 5.5: Transpose of a matrix
transpose_a = np.transpose(a)
print("\nTranspose of Matrix A:")
print(transpose_a)

# 5.6: Determinant of Matrix A
det_a = np.linalg.det(a)
print("\nDeterminant of Matrix A:")
print(det_a)

# 5.7: Inverse of Matrix A
if det_a != 0:  # Inverse exists only if determinant is non-zero
    inv_a = np.linalg.inv(a)
    print("\nInverse of Matrix A:")
    print(inv_a)
else:
    print("\nMatrix A has no inverse (Determinant is zero).")




Original Array:
[1 2 3 4 5 6 7 8 9]

Resized to 3x3 Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Random 3x3 Matrix:
[[8 9 9]
 [2 1 2]
 [8 3 7]]

Matrix Addition (A + B):
[[ 9 11 12]
 [ 6  6  8]
 [15 11 16]]

Matrix Subtraction (A - B):
[[-7 -7 -6]
 [ 2  4  4]
 [-1  5  2]]

Matrix Multiplication (a * b):
[[ 36  20  34]
 [ 90  59  88]
 [144  98 142]]

Cross Product (Row-wise A x B):
[[ -9  15  -7]
 [  4   4  -6]
 [ 29  23 -43]]

Transpose of Matrix A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Determinant of Matrix A:
0.0

Matrix A has no inverse (Determinant is zero).
